name: Visit URL
on:
  schedule:
    - cron: "*/2 * * * *" # Runs at 00:00 UTC every 2'

jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      # Add your job steps here
      - run: wget -O - https://today-tia-learned.netlify.app/ >/dev/null 2>&1
