name: CRON Jobs

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00" (see https://crontab.guru)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: visit url
        # Hit the url to keep the site active and avoid supabase deactivation
        run: curl https://today-tia-learned.netlify.app/
